//short-links 리퀘스트


POST http://localhost:3000/api/short-links
Content-Type: application/json

{
  "title": "코드잇 커뮤니티",
  "url" : "https://www.cdeit.kr/community/general"
}

###

GET http://localhost:3000/api/short-links/6734ad0d99da7cfd1eb43cf9

###

GET http://localhost:3000/api/short-links


###

PATCH  http://localhost:3000/api/short-links/6734b1b699da7cfd1eb43cfc
Content-Type: application/json

{
  "title":"netflix",
  "url":"https://www.netflix.com"
}
###

DELETE http://localhost:3000/api/short-links/6734b43999da7cfd1eb43d01









// qrcodes 리퀘스트

###

POST http://localhost:3000/api/qrcodes
Content-Type: application/json

{
  "title": "네이버 ",
  "url" : "https://www.naver.com"
}

###

GET http://localhost:3000/api/qrcodes

###

PATCH  http://localhost:3000/api/qrcodes/6735742f8c1c15f2adcf49d2
Content-Type: application/json

{
  "title": "코드잇 커뮤니티 - 수정",
  "url": "https://www.codeit.kr/community/general"
}

###

DELETE  http://localhost:3000/api/qrcodes/6735742f8c1c15f2adcf49d2